### ISSUE TITLE
Cookie consent image causes small CLS

### ISSUE THREAD

**Issue by paolomoz** [hlxsites/ororafresh#111]
<img width="886" alt="Screenshot 2023-07-18 at 10 04 26" src="https://github.com/hlxsites/ororafresh/assets/111385/53d85d63-acd2-4d9a-8a86-85c6952c30fc">

**Comment by meejain** [comment]
@paolomoz - with regards to the image for the Cookie Preference icon, its an issue with the image itself. Despite decreasing the size of the DIV, still that image will pop up like that on the right and the bottom since that image cuttings are like that only. Please check the attached screenshots - 

<img width="1205" alt="image" src="https://github.com/hlxsites/ororafresh/assets/37831850/0539e05f-1182-44af-b413-5fc571a611a7">
<img width="1528" alt="image" src="https://github.com/hlxsites/ororafresh/assets/37831850/f830c42b-5064-4748-a770-9295675a45e5">

**Comment by paolomoz** [comment]
I think this is fixed with https://github.com/hlxsites/ororafresh/pull/117
