### ISSUE TITLE
Cookie Consent

### ISSUE THREAD

**Issue by paolomoz** [hlxsites/ororafresh#15]
probably in delay.js see https://cq-dev.slack.com/archives/C9KD0TT6G/p1681317346812979

**Comment by meejain** [comment]
With regards to Cookie Consent Code, got few queries - 

1) Do we need to write a JS Code - which creates DOM elements over the footer & then act accordingly OR we can leverage any of our by default block element to build its structure let say column which will have 
2) Can we add something like Cookie.JS under scripts folder which targets footer as its parent ? 

Once tested successfully, then we can add that code under delayed.js file. Please advise. 

Also need some clarification on cookie expiration time frames - 30 days ? 

Many Thanks, 

Meet

**Comment by paolomoz** [comment]
I don't know yet how to do this (first time)
My best guess is that we have to reverse engineer the TrustArc integration and see what happens https://trustarc.com/
We can also ask the customer how it is implemented and we might have to do the same.
First option as usual is to check on #franklin-chat what others did

**Comment by meejain** [comment]
I did check in the franklin chat group and got the below guidelines with another third party cookie provider - usercentric. 

Engineering has done this via loading in delay.js as per below - 

https://github.com/hlxsites/sunstar-engineering/blob/c2f9c6ac2c14a047c9dcfc9e5cb8efae59320263/scripts/scripts.js#L423

https://github.com/hlxsites/sunstar-engineering/blob/c2f9c6ac2c14a047c9dcfc9e5cb8efae59320263/scripts/delayed.js#L26

Will try configuring the above on my new test branch - cookie-consent-15 and validate further. And accordingly, come back with doubts. Plus along with that, we need to configure GA as well so that both implementations go side by side. 

Will keep you posted @paolomoz  

Many Thanks, 

Meet

**Comment by meejain** [comment]
https://github.com/hlxsites/ororafresh/pull/77 - issue is fixed now. 

https://cookie-consent-15--ororafresh--hlxsites.hlx.page/Drafts/Meet/
