### ISSUE TITLE
Hero Carousel

### ISSUE THREAD

**Issue by paolomoz** [hlxsites/ororafresh#17]

**Comment by paolomoz** [comment]
@meejain you can assign yourself

**Comment by meejain** [comment]
Carousel is ready now. Please check - https://hero-carousel-17--ororafresh--hlxsites.hlx.page/Drafts/Meet/

I need to disable autoblocking in order to implement the above otherwise, it was taking my 1st image of Carousel as HERO image. 

The above tests are hence giving red flags for - 

1) Intendation 
2) buildAutoBlocks is not used by defined. 

Please advise, if we may ignore them via ESLint . 

Regards,

Meet
